import type { CapturedScreenshot } from "./types.ts";

export function renderIndexMd(area: string, captures: readonly CapturedScreenshot[]): string {
  const sorted = [...captures].sort((a, b) => {
    if (a.routeSlug !== b.routeSlug) return a.routeSlug.localeCompare(b.routeSlug);
    return a.viewport.localeCompare(b.viewport);
  });
  const lines: string[] = [];
  lines.push(`# ${area} screenshot catalog`);
  lines.push("");
  lines.push("Auto-generated by `tools/screenshots/src/crawl.ts`. Do not hand-edit;");
  lines.push("regenerate via `npm run screenshots -- --target=<area>`.");
  lines.push("");
  lines.push("| Route slug | Viewport | Path | File | Description |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const c of sorted) {
    const file = relativeOutPath(c.filePath);
    lines.push(
      `| \`${c.routeSlug}\` | ${c.viewport} | \`${c.routePath}\` | [\`${file}\`](./${file}) | ${escapePipe(c.routeDescription)} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function relativeOutPath(absOrRel: string): string {
  const normalized = absOrRel.replace(/\\/g, "/");
  const tail = normalized.split("/").slice(-2).join("/");
  return tail;
}

function escapePipe(s: string): string {
  return s.replace(/\|/g, "\\|");
}
