export default {
  index: "Introduction",
  "getting-started": "Getting started",
  tutorial: "Tutorial",
  "core-concepts": "Core concepts",
  "security-model": "Security model",
  "self-host": "Self-hosting",
  provisioning: "Provisioning an existing app",
  sdk: "SDK",
  react: "React",
  browser: "Browser (plain JS)",
  roblox: "Roblox",
  cpp: "C++",
  unreal: "Unreal Engine",
  "api-reference": "API",
  auth: "Auth",
  pagination: "Pagination",
  "feature-matrix": "Feature matrix",
  versioning: "Versioning",
  limits: "Limits",
  troubleshooting: "Troubleshooting",
};
